fix = true
show-fixes = true
target-version = "py311"

[format]
docstring-code-format = true

[lint]
ignore = [
  "ANN",
  "ARG",
  "BLE",
  "COM",
  "D1",
  "ERA",
  "FIX",
  "ISC",
  "PLR09",
  "PLR2004",
  "S",
  "T20",
  "TD",
]
select = ["ALL"]

[lint.pydocstyle]
convention = "google"
