version: "3"

tasks:
  assets:
    cmds:
      - bash scripts/deploy-gh-pages.sh demo assets

  build:
    cmds:
      - poetry build

  clean:
    cmds:
      - git clean -d --force -X

  demo:
    cmds:
      - vhs demo/demo.tape

  dist:
    cmds:
      - bash scripts/dist.sh "{{OS}}" "{{ARCH}}" "{{.PYTHON_VERSION}}" "{{exeExt}}"
    vars:
      PYTHON_VERSION:
        sh: python scripts/python_version.py

  publish:
    cmds:
      - poetry publish --build

  setup:
    cmds:
      - micromamba --yes --name="ai-commit-cli" create libpython-static python=3.11
      - micromamba --yes --name="ai-commit-cli" run poetry install
