name: CI

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rye
        uses: eifinger/setup-rye@v3
      - name: Install Dependencies
        run: rye sync
      - name: Build Package
        run: rye build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  release-please:
    name: Release Please
    permissions:
      contents: write
      pull-requests: write
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    outputs:
      created: ${{ steps.release.outputs.releases_created }}
      pr: ${{ steps.release.outputs.pr }}
      tag: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: release
        name: Release Please
        uses: google-github-actions/release-please-action@v4
        with:
          config-file: .github/release-please/config.json
          manifest-file: .github/release-please/.manifest.json

  pre-release:
    name: Pre-release
    permissions:
      contents: write
    needs:
      - build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Create GitHub Release
        uses: liblaf/repo/.github/actions/release@main
        with:
          tag: dev
          files: dist/*
          pre-release: true
          recreate: true

  publish:
    name: Publish
    permissions:
      id-token: write
    needs:
      - build
      - release-please
    if: needs.release-please.outputs.created == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  release:
    name: Release
    permissions:
      contents: write
    needs:
      - build
      - release-please
    if: needs.release-please.outputs.created == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Create GitHub Release
        uses: liblaf/repo/.github/actions/release@main
        with:
          tag: ${{ needs.release-please.outputs.tag }}
          files: dist/*
