name: CI

on:
  push:

jobs:
  build:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rye
        uses: eifinger/setup-rye@v2
      - name: Install Dependencies
        run: rye sync
      - name: Build Package
        run: rye run bash "scripts/dist.sh"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pkg-py${{ matrix.python-version }}
          path: dist/*
    strategy:
      matrix:
        python-version:
          - "3.11"

  release:
    name: Release
    permissions:
      contents: write
    needs:
      - build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Create GitHub Release
        uses: liblaf/repo/.github/actions/release@main
        with:
          tag: dev
          files: "*"
          prerelease: true
          recreate: true
