name: CI

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build-pkg:
    name: Build Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: Install Tools
        uses: liblaf/template/.github/actions/install@main
        with:
          other: poetry task
      - name: Install Dependencies
        run: poetry install
      - name: Build Package
        run: poetry run task build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pkg-py${{ matrix.python-version }}
          path: dist/*
    strategy:
      matrix:
        python-version:
          - "3.11"

  build-exe:
    name: Build Executable
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: Install Tools
        uses: liblaf/template/.github/actions/install@main
        with:
          other: poetry task
      - name: Install Dependencies
        run: poetry install
      - name: Build Executable
        run: poetry run task dist
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-${{ runner.arch }}-py${{ matrix.python-version }}
          path: dist/*
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"

  release:
    name: Release
    permissions:
      contents: write
    needs:
      - build-pkg
      - build-exe
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Create GitHub Release
        uses: liblaf/template/.github/actions/release@main
        with:
          tag: dev
          files: "*"
          prerelease: true
