name: Merge

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Check
        uses: liblaf/template/.github/actions/check@main
        with:
          pr: ${{ github.event.pull_request.html_url }}

  merge:
    name: Merge
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Enable Auto-Merge (Squash)
        uses: liblaf/template/.github/actions/merge@main
        with:
          pr: ${{ github.event.pull_request.html_url }}
          user: ${{ github.event.pull_request.user.login }}
