name: Stale

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  stale:
    name: Stale
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Stale
        uses: actions/stale@v9
