name: Repository Template

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  template:
    name: Template
    permissions:
      actions: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Sync with Repository Template
        uses: liblaf/template@main
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit: true
